name: HTML CSS valid

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests Integration with Github Actions.
        uses: Cyb3r-Jak3/html5validator-action-experimental@master
        with:
          root: ./
          css: true
          extra: "--ignore-re 'Property \"translate\" doesn\\'t exist'"
